Merge with trunk 31445
git-svn-id: https://root.cern.ch/svn/root/branches/dev@31446 27541ba8-7e3a-0410-8455-c3a389f83636

diff --git a/mathDev/configure b/mathDev/configure
--- a/mathDev/configure
+++ b/mathDev/configure
@@ -63,6 +63,7 @@ options="                    \
    enable_glite              \
    enable_globus             \
    enable_gsl_shared         \
+   enable_hdfs               \
    enable_krb5               \
    enable_ldap               \
    enable_mathmore           \
@@ -153,6 +154,7 @@ CASTOR           \
 GFAL             \
 G4ROOT           \
 GSL              \
+HDFS             \
 PYTHIA6          \
 PYTHIA8          \
 FFTW3            \
@@ -988,7 +990,7 @@ fi
 confhelp() {
 vers=`cat build/version_number`
 cat <<EOF
-\`configure' configures ROOT $vers to adapt to many kind of systems.
+'configure' configures ROOT $vers to adapt to many kind of systems.
 
 Usage:     $0 [architecture] [flag=value]
 
@@ -1057,6 +1059,7 @@ enable/disable options, prefix with either --enable- or --disable-
   globus             Globus authentication support, requires Globus toolkit
   glite              gLite support, requires libglite-api-wrapper v.3 from GSI (https://subversion.gsi.de/trac/dgrid/wiki)
   gsl-shared         enable linking against shared libraries for GSL (default no)
+  hdfs               HDFS support; requires libhdfs from HDFS >= 0.19.1
   krb5               Kerberos5 support, requires Kerberos libs
   ldap               LDAP support, requires (Open)LDAP libs
   genvector          Build the new libGenVector library
@@ -1134,6 +1137,10 @@ with options, prefix with --with-, enables corresponding support
   globus             Globus support, path to what should be GLOBUS_LOCATION
   globus-incdir      Globus support, location of globus header files
   globus-libdir      Globus support, location of globus libraries
+  hdfs-incdir        HDFS support, location of hdfs.h
+  hdfs-libdir        HDFS support, location of libhdfs
+  jni-incdir         HDFS support, location of JNI headers
+  jvm-libdir         HDFS support, location of JVM library
   krb5               Kerberos5 support, location of Kerberos distribution
   krb5-incdir        Kerberos5 support, location of krb5.h
   krb5-libdir        Kerberos5 support, location of libkrb5
@@ -1359,6 +1366,10 @@ if test $# -gt 0 ; then
       --with-globus-incdir=*)  globusincdir=$optarg  ; enable_globus="yes"    ;;
       --with-globus-libdir=*)  globuslibdir=$optarg  ; enable_globus="yes"    ;;
       --with-gccxml=*)         gccxml=$optarg        ;;
+      --with-hdfs-incdir=*)    hdfsincdir=$optarg    ; enable_hdfs="yes"    ;;
+      --with-hdfs-libdir=*)    hdfslibdir=$optarg    ; enable_hdfs="yes"    ;;
+      --with-jni-incdir=*)     jniincdir=$optarg     ;;
+      --with-jvm-libdir=*)     jvmlibdir=$optarg     ;;
       --with-krb5=*)           krb5dir=$optarg       ; enable_krb5="yes"    ;;
       --with-krb5-incdir=*)    krb5incdir=$optarg    ; enable_krb5="yes"    ;;
       --with-krb5-libdir=*)    krb5libdir=$optarg    ; enable_krb5="yes"    ;;
@@ -2758,27 +2769,30 @@ if test ! "x$enable_gviz" = "xno"; then
 
     # At this time, libgvplugin_core.a should always be prefered over .so,
     # to avoid forcing users to install graphviz.
-    check_library "libgvc" "no" "$gvizlibdir" $GVIZ $GVIZ/lib \
+    check_library "libgvc gvc" "no" "$gvizlibdir" $GVIZ $GVIZ/lib \
                   $GVIZ/.libs /usr/local/lib /usr/lib /opt/local/lib
     gvizlib1=$found_lib
     gvizlib1raw=$found_raw_lib
     gvizlibir=$found_dir
-    check_library "libgraph" "no" "$gvizlibdir" $GVIZ $GVIZ/lib \
+    check_library "libgraph graph" "no" "$gvizlibdir" $GVIZ $GVIZ/lib \
                   $GVIZ/.libs /usr/local/lib /usr/lib /opt/local/lib
     gvizlib2=$found_lib
-    check_library "libcdt" "no" "$gvizlibdir" $GVIZ $GVIZ/lib \
+    check_library "libcdt cdt" "no" "$gvizlibdir" $GVIZ $GVIZ/lib \
                   $GVIZ/.libs /usr/local/lib /usr/lib /opt/local/lib
     gvizlib3=$found_lib
-    check_library "libpathplan" "no" "$gvizlibdir" $GVIZ $GVIZ/lib \
+    check_library "libpathplan pathplan" "no" "$gvizlibdir" $GVIZ $GVIZ/lib \
                   $GVIZ/.libs /usr/local/lib /usr/lib /opt/local/lib
     gvizlib4=$found_lib
 
-       # the plugin libraries are in the directory "$gvizlibdir"/graphviz
-       gvizlibpdir=""
-       if test "x$gvizlibdir" != "x" ; then
-           gvizlibpdir="$gvizlibdir"/graphviz
-       fi
-    check_library "libgvplugin_dot_layout" "no" "$gvizlibpdir" $GVIZ $GVIZ/lib \
+    # the plugin libraries are in the directory "$gvizlibdir"/graphviz
+    gvizlibpdir=""
+    if test "x$gvizlibdir" != "x" ; then
+        gvizlibpdir="$gvizlibdir"/graphviz
+    fi
+    if test "x$platform" = "xwin32"; then
+        gvizlibpdir="$gvizlibdir"
+    fi
+    check_library "libgvplugin_dot_layout gvplugin_dot_layout" "no" "$gvizlibpdir" $GVIZ $GVIZ/lib \
                   $GVIZ/.libs /usr/local/lib/graphviz /usr/lib/graphviz \
                   /opt/local/lib/graphviz
     gvizlibp1=$found_lib
@@ -2786,17 +2800,25 @@ if test ! "x$enable_gviz" = "xno"; then
 
     if test "x$gvizincdir" = "x" || test "x$gvizlib1"  = "x" ||
        test "x$gvizlib2"   = "x" || test "x$gvizlib3"  = "x" ||
-       test "x$gvizlib4"   = "x" || test "x$gvizlibp1" = "x" ; then
+       test "x$gvizlib4"   = "x" ; then
         enable_gviz="no"
     else
        for gvsharedext in .so .sl .dylib .dll.a; do
            gvizshared="$gvizshared`echo $gvizlib1raw | grep '\\'$gvsharedext'\$'`"
        done
        if test "x$gvizshared" = "x" ; then
-           gvizcflags=-DGVIZ_STATIC
-           gvizlib="$gvizlibp1 $gvizlib1 $gvizlib2 $gvizlib3 $gvizlib4 -lexpat"
+           if test "x$gvizlibp1" = "x" ; then
+               enable_gviz="no"
+           else
+               gvizcflags=-DGVIZ_STATIC
+               gvizlib="$gvizlibp1 $gvizlib1 $gvizlib2 $gvizlib3 $gvizlib4 -lexpat"
+           fi
        else
            gvizlib="$gvizlibir $gvizlib1"
+       fi
+       if test "x$platform" = "xwin32"; then
+           gvizcflags=
+           gvizlib="$gvizlibp1 $gvizlib1 $gvizlib2 $gvizlib3 $gvizlib4"
        fi
     fi
 fi
@@ -2952,6 +2974,89 @@ if test ! "x$enable_chirp" = "xno" ; then
 fi
 check_explicit "$enable_chirp" "$enable_chirp_explicit" \
      "Explicitly required Chirp dependencies not fulfilled"
+
+######################################################################
+#
+### echo %%% HDFS Support - Third party libraries
+#
+# (See http://hadoop.apache.org/hdfs)
+#
+# Check for hdfs.h of HDFS and libhdfs
+#
+if test ! "x$enable_hdfs" = "xno" ; then
+    # Check for hdfs include and library
+    keepincdir=$hdfsincdir
+    check_header "hdfs.h" "$hdfsincdir" $HDFS $HDFS/include $HDFS/src/c++/libhdfs \
+        $HADOOP_HOME $HADOOP_HOME/src/c++/libhdfs /usr/include \
+        /usr/local/include
+    hdfsinc=$found_hdr
+    hdfsincdir=$found_dir
+
+    keepincdir=$jniincdir
+    check_header "jni.h" "$jniincdir" $JAVA_HOME/include \
+        /usr/java/default/include /usr/include /usr/local/include
+    jniinc=$found_hdr
+    jniincdir=$found_dir
+
+    check_library "libhdfs" "$enable_shared" \
+        "$hdfslibdir" \
+        $HDFS $HDFS/lib $HDFS/build/libhdfs $HADOOP_HOME $HADOOP_HOME/build/libhdfs \
+        /usr/lib /usr/local/lib
+    hdfslib=$found_lib
+    hdfslibdir=$found_dir
+
+    check_library "libjvm" "$enable_shared" \
+        "$jvmlibdir" \
+        $JAVA_HOME/jre/lib/amd64/server $JAVA_HOME/jre/lib/i386/server \
+        /usr/java/default/jre/lib/amd64/server \
+        /usr/java/default/jre/lib/i386/server /usr/lib /usr/local/lib
+    jvmlib=$found_lib
+    jvmlibdir=$found_dir
+
+    if test "x$hdfsincdir" = "x" || test "x$hdfslib" = "x" || test "x$jniincdir" = "x" || test "x$jvmlib" = "x"; then
+        enable_hdfs="no"
+    else
+        case $platform in
+           linux)
+                hdfslib="$hdfslib"
+                for i in "" -ladns ; do
+                    echo 'extern hdfsConnect(const char *, uint16_t); int main() { hdfsConnect("default", 0); return 0; }' > conftest.c
+                    logmsg " Checking if we can link against $hdfslib"
+                    logmsg " gcc conftest.c $hdfslibdir $hdfslib $i -o conftest"
+                    gcc conftest.c $hdfslibdir $hdfslib $i -o conftest >> $logfile 2>&1
+                    if test $? -eq 0 ; then
+                        hdfslib="$hdfslib $i" ;
+                        break ;
+                    else
+                        logmsg " Failed program was:"
+                        cat conftest.c >> $logfile
+                        enable_hdfs="no"
+                    fi
+                done
+                rm -f conftest.c conftest
+
+                jvmlib="$jvmlib"
+                for i in "" -ladns ; do
+                    echo '#include "jni.h"; extern JNI_CreateJavaVM(JavaVM*, JNIEnv*, JavaVMInitArgs*); int main() { JNI_CreateJavaVM(NULL, NULL, NULL); return 0; }' > conftest.c
+                    logmsg " Checking if we can link against $jvmlib"
+                    logmsg " gcc conftest.c $jniincdir $jvmlibdir $jvmlib $i -o conftest"
+                    gcc conftest.c $jvmlibdir $jvmlib $i -o conftest >> $logfile 2>&1
+                    if test $? -eq 0 ; then
+                        jvmlib="$jvmlib $i" ;
+                        break ;
+                    else
+                        logmsg " Failed program was:"
+                        cat conftest.c >> $logfile
+                        enable_hdfs="no"
+                    fi
+                done
+                rm -f conftest.c conftest
+                ;;
+        esac
+    fi
+fi
+check_explicit "$enable_hdfs" "$enable_hdfs_explicit" \
+     "Explicitly required HDFS dependencies not fulfilled"
 
 ######################################################################
 #
@@ -4638,8 +4743,25 @@ fi
 #
 message "Checking whether to build libCintex"
 if test ! "x$enable_cintex" = "xno"; then
-    enable_cintex="yes"
-    result "yes"
+    # only enable on i386, i686, x86_64:
+    case "$chip" in
+        i*86 | x86_64)
+            enable_cintex="yes"
+            result "yes"
+            ;;
+        *)
+            case `uname -m` in
+                i*86 | x86_64)
+                    enable_cintex="yes"
+                    result "yes"
+                    ;;
+                *)
+                    logmsg " incompatible Cintex architecture $chip"
+                    enable_cintex=""
+                    result "no"
+                    ;;
+            esac
+     esac
 else
     enable_cintex=""
     result "no"
@@ -4925,6 +5047,7 @@ if test "x$show_pkglist" = "xyes" ; then
     test "x$enable_chirp"    = "xyes" && pl="$pl root-plugin-io-chirp"
     test "x$enable_dcache"   = "xyes" && pl="$pl root-plugin-io-dcache"
     test "x$enable_gfal"     = "xyes" && pl="$pl root-plugin-io-gfal"
+    test "x$enable_hdfs"     = "xyes" && pl="$pl root-plugin-io-hdfs"
     test "x$enable_rfio"     = "xyes" && pl="$pl root-plugin-io-rfio"
     test "x$enable_fftw3"    = "xyes" && pl="$pl root-plugin-math-fftw3"
     test "x$enable_gviz"     = "xyes" && pl="$pl root-plugin-graf2d-gviz"
@@ -5094,6 +5217,9 @@ if test -d pcre/src/pcre-6.4 ; then
 fi
 if test -d core/pcre/src/pcre-7.4 ; then
    rm -rf core/pcre/src/pcre-7.4
+fi
+if test -d math/unuran/src/unuran-1.3.0-root ; then
+   rm -rf math/unuran/src/unuran-1.3.0-root
 fi
 if test ! "x$enable_editline" = "xno" ; then
    rm -f core/clib/src/Getline.o core/clib/src/Getline.d
@@ -5362,8 +5488,14 @@ sed -e "s|@globusincdir@|$globusincdir|"        \
     -e "s|@glbextracflags@|$glbextracflags|"    \
     -e "s|@glbpatchcflags@|$glbpatchcflags|"    \
     -e "s|@gccxml@|$gccxml|"                    \
+    -e "s|@hdfsincdir@|$hdfsincdir|"            \
+    -e "s|@hdfslib@|$hdfslib|"                  \
+    -e "s|@hdfslibdir@|$hdfslibdir|"            \
     -e "s|@iconpath@|$iconpath|"                \
     -e "s|@incdir@|$incdir|"                    \
+    -e "s|@jniincdir@|$jniincdir|g"             \
+    -e "s|@jvmlibdir@|$jvmlibdir|g"             \
+    -e "s|@jvmlib@|$jvmlib|g"                   \
     -e "s|@krb5incdir@|$krb5incdir|"            \
     -e "s|@krb5lib@|$krb5lib|"                  \
     -e "s|@krb5libdir@|$krb5libdir|"            \
@@ -5488,6 +5620,7 @@ sed -e "s|@srcdir@|$srcdir|"                    \
     -e "s|@buildg4root@|$enable_g4root|"        \
     -e "s|@buildbonjour@|$enable_bonjour|"      \
     -e "s|@buildchirp@|$enable_chirp|"          \
+    -e "s|@buildhdfs@|$enable_hdfs|"            \
     -e "s|@buildalien@|$enable_alien|"          \
     -e "s|@buildasimage@|$enable_asimage|"      \
     -e "s|@buildpythia6@|$enable_pythia6|"      \
