synchronize with trunk HEAD, revision 26021
git-svn-id: https://root.cern.ch/svn/root/branches/dev/mathDev@26022 27541ba8-7e3a-0410-8455-c3a389f83636

diff --git a/cint/configure b/cint/configure
--- a/cint/configure
+++ b/cint/configure
@@ -156,7 +156,7 @@ function config_macos {
     MACOSX_MINOR=`sw_vers | sed -n 's/ProductVersion://p' | cut -d . -f 2`
     if [ `echo $MACOSX_MINOR | cut -d ' ' -f 2` -gt 4 ]; then
         # this is set for 64 but not for 32  bit
-        CFLAGS="${CFLAGS} -D__DARWIN_UNIX03=1"
+        CMACROS="${CMACROS} -D__DARWIN_UNIX03=1"
         CXXFLAGS="${CXXFLAGS} -D__DARWIN_UNIX03=1"
     fi
 }
@@ -166,7 +166,7 @@ function config_macosx64 {
     CFLAGS="${CFLAGS} -m64"
     CXXFLAGS="${CXXFLAGS} -m64"
     LDFLAGS="${LDFLAGS} -m64"
-    SOFLAGS="${SOFLAGS -m64}"
+    SOFLAGS="${SOFLAGS} -m64"
 }
 
 function config_djgpp {
@@ -482,38 +482,45 @@ function processflag_with_prefix {
 }
 
 function processflag_prefix {
+    WITHPREFIX=1
     pathtoabs $1
     PREFIX=$ABSPATH
 }
 
 function processflag_exec_prefix {
+    WITHPREFIX=1
     pathtoabs $1
     EPREFIX=$ABSPATH
 }
 
 function processflag_bindir {
+    WITHPREFIX=1
     pathtoabs $1
     BINDIR=$ABSPATH
 }
 
 function processflag_libdir {
+    WITHPREFIX=1
     pathtoabs $1
     LIBDIR=$ABSPATH
 }
 
 function processflag_includedir {
+    WITHPREFIX=1
     pathtoabs $1
     INCLUDEDIR=$ABSPATH
     INCLUDEDIRCINT=$ABSPATH/cint
 }
 
 function processflag_datadir {
+    WITHPREFIX=1
     pathtoabs $1
     DATADIR=$ABSPATH
     DATADIRCINT=$ABSPATH/cint
 }
 
-function processflag_datadir {
+function processflag_mandir {
+    WITHPREFIX=1
     pathtoabs $1
     MANDIR=$ABSPATH
 }
@@ -675,8 +682,17 @@ EXPORTS=(${EXPORTS[*]} HAVE_CONFIG)
 # now set the default values of the installation directories, if
 # they were not set explicitely by the user
 
-if [ "x$PREFIX" != "x" ]; then
+if [ "x$WITHPREFIX" = "x1" ]; then
   # prefix based build
+    [ "$PREFIX" = "" ] && PREFIX=/usr/local
+    if [ -d "$PREFIX" -a "`cd \"$PREFIX\"; pwd`" = "`cd \"$PWD\"; pwd`" ]; then
+        echo ' '
+        echo ' '
+        echo 'ERROR: Cannot build within install location!'
+        echo 'Directory '$PREFIX' set as --prefix is the same as the current directory!'
+        echo ' '
+        exit 1
+    fi
     [ "$EPREFIX" = "" ] && EPREFIX=$PREFIX
     [ "$BINDIR" = "" ]  && BINDIR=$EPREFIX/bin
     [ "$LIBDIR" = "" ]  && LIBDIR=$EPREFIX/lib
@@ -693,7 +709,8 @@ if [ "x${COREVERSION}" = "xcint" ]; then
 else
   CINTVERSIONTAG=G__CINTVERSIONSTR
 fi
-CINTVERSION=`grep '#define *'${CINTVERSIONTAG}' ' ${COREVERSION}/inc/G__ci.h | sed 's/^.*"\([^,]\+\),.*$/\1/'`
+
+CINTVERSION=`grep '#define *'${CINTVERSIONTAG}' ' ${COREVERSION}/inc/G__ci.h | sed 's/^.*"\([^,]*\),.*$/\1/'`
 
 
 #############################################################
@@ -787,6 +804,18 @@ echo ${ALLOPTIONS[*]} > config.status
 
 echo Creating Makefile...
 cp build/Makefile .
+
+echo Creating reconfigure...
+# we need the "&& exit" below to ensure that the shell doesn't
+# continue reading reconfigure, where reconfigure will be the
+# one recreated by the sub-configure:
+cat > reconfigure <<EOF
+echo Reconfiguring with
+echo '  $' ./configure ${ALLOPTIONS[*]} "\$@"
+echo ' '
+./configure ${ALLOPTIONS[*]} "\$@" && exit
+EOF
+chmod u+x reconfigure
 
 echo Done.
 echo ""
