merge with the trunk , revision 31888 (at release 5.26)
git-svn-id: https://root.cern.ch/svn/root/branches/dev/mathDev@31889 27541ba8-7e3a-0410-8455-c3a389f83636

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -267,6 +267,49 @@ checking_msg() {
 }
 
 #_____________________________________________________________________
+check_libpic() {
+    # This function will try to find out if an archive library [$1]
+    # contains relocatable code. Currently works only for linux.
+    # The result of the check is stored in is_libpic, 1 if true,
+    # 0 otherwise, which should be immediately copied, since the variable
+    # will be overwritten at next invocation of this function.
+
+    is_libpic=1
+
+    # Assert that we got enough arguments
+    if test $# -ne 1 ; then
+        echo "check_libpic: not 1 argument"
+        return 1
+    fi
+
+    case $platform in
+    linux) ;;
+    *)     return 0;
+           ;;
+    esac
+
+    # Save arguments in logical names
+    chklibpic=$1
+    if [ "x`basename $chklibpic .a`" != "x`basename $chklibpic`" ]; then
+        # we have an archive .a file
+        logmsg "Checking if $chklibpic contains relocatable code"
+        logmsg " ar t $chklibpic | awk '{ if (NR==1) {print \$1 } }'"
+        objpic=`ar t $chklibpic | awk '{ if (NR==1) {print $1 } }'`
+        logmsg " ar x $chklibpic $objpic"
+        ar x $chklibpic $objpic
+        logmsg " objdump -r $objpic | grep 'R_X86_64_32'"
+        objdump -r $objpic | grep 'R_X86_64_32' > /dev/null 2>& 1
+        ret=$?
+        rm -f $objpic
+        logmsg " result: $ret"
+        if test $ret -eq 0 ; then
+            is_libpic=0
+            logmsg " is not a relocatable library"
+        fi
+    fi
+}
+
+#_____________________________________________________________________
 check_lib64() {
     # This function will try to find out if a library [$1] contains 64 bit
     # or 32 bit code. Currently works only for linux.
@@ -2386,7 +2429,7 @@ if test ! "x$enable_qt" = "xno" || \
             check_library "libQtCore QtCore QtCore$qt4suffix QtCore4" \
                 "$enable_shared" \
                 "$qtlibdir" $QTDIR $QTDIR/lib /usr/local/lib \
-                /usr/local/qt/lib /usr/lib /usr/qt/lib
+                /usr/local/qt/lib /usr/lib /usr/qt/lib /usr/lib/qt4
             qtlib=$found_lib
             qtlibdir=$found_dir
             check_library "libQtGui QtGui QtGui$qt4suffix QtGui4" \
@@ -2670,14 +2713,15 @@ if test ! "x$enable_g4root" = "xno"; then
         G4SYSLIBDIR=$G4LIB/$G4SYSTEM
     fi
     check_library "libG4navigation" "$enable_shared" "$g4libdir" \
-        $G4SYSLIBDIR /opt/geant4/lib /opt/g4/lib /usr/local/lib /usr/lib
+        $G4SYSLIBDIR /opt/geant4/lib /opt/g4/lib /usr/local/lib /usr/lib \
+        /usr/lib/geant4
 
     g4rootlib=$found_lib
     g4libdir=$found_dir
 
     # Check for CLHEP include
     check_header "CLHEP/Vector/Rotation.h" "$clhepincdir" "$clhepincdir" \
-        $CLHEP_INCLUDE_DIR
+        $CLHEP_INCLUDE_DIR /usr/include
     clhepinc=$found_hdr
     clhepincdir=$found_dir
 
@@ -2895,7 +2939,7 @@ check_explicit "$enable_pythia6" "$enable_pythia6_explicit" \
 if test ! "x$enable_pythia8" = "xno" ; then
     # Check for PYTHIA8 include and library
     check_header "Pythia.h" "$pythia8incdir" $PYTHIA8 $PYTHIA8/include \
-        /opt/pythia8/include /usr/local/include /usr/include
+        /opt/pythia8/include /usr/local/include /usr/include /usr/include/pythia
     pythia8incdir=$found_dir
 
     check_library "libpythia8" "$enable_shared" "$pythia8libdir" \
@@ -3020,7 +3064,7 @@ if test ! "x$enable_hdfs" = "xno" ; then
            linux)
                 hdfslib="$hdfslib"
                 for i in "" -ladns ; do
-                    echo 'extern hdfsConnect(const char *, uint16_t); int main() { hdfsConnect("default", 0); return 0; }' > conftest.c
+                    echo 'extern hdfsConnect(const char *, unsigned short); int main() { hdfsConnect("default", 0); return 0; }' > conftest.c
                     logmsg " Checking if we can link against $hdfslib"
                     logmsg " gcc conftest.c $hdfslibdir $hdfslib $i -o conftest"
                     gcc conftest.c $hdfslibdir $hdfslib $i -o conftest >> $logfile 2>&1
@@ -3037,10 +3081,11 @@ if test ! "x$enable_hdfs" = "xno" ; then
 
                 jvmlib="$jvmlib"
                 for i in "" -ladns ; do
-                    echo '#include "jni.h"; extern JNI_CreateJavaVM(JavaVM*, JNIEnv*, JavaVMInitArgs*); int main() { JNI_CreateJavaVM(NULL, NULL, NULL); return 0; }' > conftest.c
+                    echo '#include "jni.h"' > conftest.c
+                    echo 'int main() { JNI_CreateJavaVM(NULL, NULL, NULL); return 0; }' >> conftest.c
                     logmsg " Checking if we can link against $jvmlib"
-                    logmsg " gcc conftest.c $jniincdir $jvmlibdir $jvmlib $i -o conftest"
-                    gcc conftest.c $jvmlibdir $jvmlib $i -o conftest >> $logfile 2>&1
+                    logmsg " gcc conftest.c -I$jniincdir -I$jniincdir/linux $jvmlibdir $jvmlib $i -o conftest"
+                    gcc conftest.c -I$jniincdir -I$jniincdir/linux $jvmlibdir $jvmlib $i -o conftest >> $logfile 2>&1
                     if test $? -eq 0 ; then
                         jvmlib="$jvmlib $i" ;
                         break ;
@@ -3053,6 +3098,7 @@ if test ! "x$enable_hdfs" = "xno" ; then
                 rm -f conftest.c conftest
                 ;;
         esac
+        echo "HDFS disabled due to failed compile and link test!"
     fi
 fi
 check_explicit "$enable_hdfs" "$enable_hdfs_explicit" \
@@ -3306,6 +3352,7 @@ if test ! "x$enable_python" = "xno" ; then
        $PYTHONDIR/include/python $pythonsysincdir
     pythoninc=$found_hdr
     pythonincdir=$found_dir
+    pysuffix=""
     if test "x$platform" = "xwin32"; then
        if test ! "x$mypython" = "x" && test -x "$mypython" ; then
           pythonvers=`python -c 'import sys; print sys.version[:3].replace(".","")' | tr -d '\r'`
@@ -3313,18 +3360,27 @@ if test ! "x$enable_python" = "xno" ; then
              pythonincdir=`cygpath -m $pythonincdir`
           fi
        fi
+       if test "x$enable_winrtdebug" = "xyes"; then
+          pysuffix="_d"
+       fi
     fi
 
-    check_library "python${pythonvers} libpython${pythonvers} \
-                   libpython python Python" \
+    check_library "python${pythonvers}${pysuffix} libpython${pythonvers}${pysuffix} \
+                   libpython${pysuffix} python${pysuffix} Python${pysuffix}" \
         "$enable_shared" "$pythonlibdir" $PYTHONDIR/libs $PYTHONDIR/lib \
         $PYTHONDIR $pythonsyslibdir $pythonsyslibdir/config \
-        $pythonsyslibdir2
+        $pythonsyslibdir2 /usr/lib
     pythonlib=$found_lib
     pythonlibdir=$found_dir
 
     if test "x$pythonincdir" = "x" || test "x$pythonlib" = "x"; then
         enable_python="no"
+        if test "x$platform" = "xwin32" && test "x$enable_winrtdebug" = "xyes" && \
+           test "x$pythonlib" = "x" && test ! "x$pythonincdir" = "x"; then
+               echo "INFO: Debug version of Python (python${pythonvers}${pysuffix}.lib) " \
+                    "not found! Disabling Python support. If you need it, install the " \
+                    "debug version or use --disable-winrtdebug"
+        fi
     else
         pythonlibflags=
         case $platform in
@@ -3629,8 +3685,6 @@ if test ! "x$enable_globus" = "xno"; then
          result "$GLOBUS_LOCATION"
       else
          result "no"
-         # Do not build libGlobusAuth
-         enable_globus="no"
       fi
    else
       result "$globusdir"
@@ -3643,28 +3697,43 @@ if test "x$enable_globus" = "xyes"; then
     #determine flavour tag of the building
     flavour=""
     if test "x$globusincdir" = "x" ; then
-       globusincdir=$globusdir/include
+       if test ! "x$globusdir" = "x" ; then
+          globusincdir=$globusdir/include
+       else
+          globusincdir=/usr/include
+       fi
     fi
     searchincdir="$globusincdir/gcc32 $globusincdir/gcc32dbg \
                   $globusincdir/gcc32pthr $globusincdir/gcc32dbgpthr \
                   $globusincdir/gcc64 $globusincdir/gcc64dbg \
-                  $globusincdir/gcc64pthr $globusincdir/gcc64dbgpthr"
+                  $globusincdir/gcc64pthr $globusincdir/gcc64dbgpthr \
+                  $globusincdir/globus $globusincdir"
 
     # Found the reference dir first
-    check_header "openssl/x509.h" "" "$searchincdir"
+    # Used to check for openssl/x509.h, but since we might be using
+    # the system default, we have replaced this with globus_gss_assist.h
+    check_header "globus_gss_assist.h" "" "$searchincdir"
     if test "x$found_hdr" = "x" ; then
        globusinc=""
        globusincdir=""
        enable_globus="no"
     else
-       globusinc="$globusinc $found_hdr"
-       globusincdir=$found_dir
-       if test ! "x$globusincdir" = "x" ; then
-          flavour=`basename $globusincdir`
+       flavour=`basename $found_dir`
+       if test "x$flavour" = "xglobus" ; then
+          flavour=
+          flavour_suf=
+       else
+          flavour_suf=_${flavour}
        fi
 
+       globusinc="$globusinc $found_hdr"
+       globusincdir=$found_dir
+
        # The other headers now
-       inclist="openssl/pem.h globus_gss_assist.h globus_common.h"
+       # Used to search for openssl/pem.h and globus_gss_assist.h here,
+       # but those are removed, because we might be using the openssl of the
+       # system, and we already checked for globus_gss_assist.h
+       inclist="globus_common.h"
        for i in $inclist ; do
           check_header $i "" "$globusincdir"
           if test "x$found_hdr" = "x" ; then
@@ -3703,29 +3772,40 @@ fi
 
 if test "x$enable_globus" = "xyes"; then
 
-   globuslib=""
    if test "x$globuslibdir" = "x" ; then
-       globuslibdir=$globusdir/lib
-   fi
-   if test "x$globusdir" = "x" ; then
-       globusdir=`dirname $globuslibdir`
-       echo "Globus main path set to $globusdir"
-   fi
+       if test ! "x$globusdir" = "x" ; then
+          globuslibdir=$globusdir/lib
+       else
+          globuslibdir=/usr/lib
+       fi
+    fi
+
+   globuslib=""
    searchlibdir=$globuslibdir
    globuslibdir=""
+   extra_inc=
 
-   globuslibs="libglobus_gss_assist_$flavour libglobus_gssapi_gsi_$flavour
-              libglobus_gsi_credential_$flavour libglobus_common_$flavour
-              libglobus_gsi_callback_$flavour libglobus_proxy_ssl_$flavour
-              libglobus_gsi_sysconfig_$flavour libglobus_openssl_error_$flavour
-              libglobus_gssapi_gsi_$flavour libglobus_gsi_callback_$flavour
-              libglobus_oldgaa_$flavour libglobus_gsi_cert_utils_$flavour
-              libglobus_openssl_$flavour  libglobus_gsi_proxy_core_$flavour
-              libglobus_callout_$flavour  libltdl_$flavour
-              libssl_$flavour libcrypto_$flavour"
+   globuslibs="libglobus_gss_assist${flavour_suf}
+              libglobus_gssapi_gsi${flavour_suf}
+              libglobus_gsi_credential${flavour_suf}
+              libglobus_common${flavour_suf}
+              libglobus_gsi_callback${flavour_suf}
+              libglobus_proxy_ssl${flavour_suf}
+              libglobus_gsi_sysconfig${flavour_suf}
+              libglobus_openssl_error${flavour_suf}
+              libglobus_gssapi_gsi${flavour_suf}
+              libglobus_gsi_callback${flavour_suf}
+              libglobus_oldgaa${flavour_suf}
+              libglobus_gsi_cert_utils${flavour_suf}
+              libglobus_openssl${flavour_suf}
+              libglobus_gsi_proxy_core${flavour_suf}
+              libglobus_callout${flavour_suf}
+              libltdl${flavour_suf}
+              libssl${flavour_suf}
+              libcrypto${flavour_suf}"
 
    for i in $globuslibs ; do
-      check_library $i "no" "$searchlibdir" /opt/globus /usr/lib \
+      check_library $i "$enable_shared" "$searchlibdir" /opt/globus /usr/lib \
       /usr/local/lib
       if test "x$found_lib" = "x" ; then
          globuslib=""
@@ -3737,18 +3817,31 @@ if test "x$enable_globus" = "xyes"; then
       if test "x$globuslibdir" = "x" && test ! "x$found_dir" = "x" ; then
          globuslibdir="$found_dir"
       fi
+      if test "x$extra_inc" = "x" && test ! "x$found_raw_dir" = "x" ; then
+         extra_inc=$found_raw_dir/globus/include
+      fi
    done
+
+   if test ! "x$extra_inc" = "x" ; then
+      message "Checking whether $extra_inc should be added to header path"
+      if test -d $extra_inc ; then
+         globusincdir="$globusincdir $extra_inc"
+         result "yes"
+      else
+         result "no"
+      fi
+   fi
 fi
 
 if test "x$enable_globus" = "xyes"; then
 
-   # Need to source this before init proxies
+   # Need to source this before init proxies (when not in default path)
    sourcepath=""
    if test -s $globusdir/etc/globus-user-env.sh ; then
       sourcepath="$globusdir/etc"
    fi
    if test "x$sourcepath" = "x" ; then
-      result "Checking for globus-user-env.sh ... no (cannot run as client)"
+      result "Checking for globus-user-env.sh ... no"
    else
       result "Checking for globus-user-env.sh ... $sourcepath"
    fi
@@ -3757,8 +3850,11 @@ if test "x$enable_globus" = "xyes"; then
    initpath=""
    if test -s $globusdir/bin/grid-proxy-init ; then
       initpath="$globusdir/bin"
+   elif which grid-proxy-init > /dev/null 2>&1 ; then
+      initpath=`which grid-proxy-init`
+      initpath=`dirname $initpath`
    fi
-   if test "x$sourcepath" = "x" ; then
+   if test "x$initpath" = "x" ; then
       result "Checking for grid-proxy-init ... no (cannot run as client)"
    else
       result "Checking for grid-proxy-init ... $initpath"
@@ -3787,6 +3883,18 @@ if test "x$enable_globus" = "xyes"; then
    package="globus_gsi_credential"
    version=""
 
+   message "Checking for globus-gsi-credential version"
+
+   # check if we have pkg-config
+   if `$cwhich pkg-config > /dev/null 2>&1` ; then
+      if pkg-config --exists globus-gsi-credential ; then
+         version=`pkg-config --modversion globus-gsi-credential`
+         result "$version"
+      fi
+   fi
+
+   if test "x$version" = "x" ; then
+
    # No explicit version given: try to find version out from gpt files ...
    packdir="$globusdir/etc/globus_packages/$package"
    if test -d $packdir ; then
@@ -3796,31 +3904,27 @@ if test "x$enable_globus" = "xyes"; then
             break
          fi
       done
-      version=""
-      checkminor=""
       if test ! "x$packfileinfo" = "x" ; then
          packfiletmp=`basename $packfileinfo`
          echo "Checking for $packfiletmp ... $packdir"
-         versionstring=`grep Minor $packfileinfo`
-         for i in $versionstring ; do
-            # Check for Major: only versions 0.x may need the patch
-            if test "x$checkminor" = "x" ; then
-               if test "Major=\"0\"" = "$i" ; then
-                  checkminor="yes"
-               fi
-            else
-               if test "x$checkminor" = "xyes" ; then
-                  for k in 5 7 8 9 ; do
-                     if test "Minor=\"$k\"" = "$i" ; then
-                        version="0.$k"
-                        break 2
-                     fi
-                  done
-               fi
-            fi
-         done
+         versionstr=`grep Aging_Version $packfileinfo`
+         majorversion=`echo $versionstr | sed 's!.*Major="\([0-9]*\)".*!\1!'`
+         minorversion=`echo $versionstr | sed 's!.*Minor="\([0-9]*\)".*!\1!'`
+         version=$majorversion.$minorversion
+         result "$version"
       fi
-      if test "x$version" = "x" ; then
+   fi
+
+   fi
+
+   if test ! "x$version" = "x" ; then
+      versionmajor=`echo $version | cut -d. -f1`
+      versionminor=`echo $version | cut -d. -f2`
+      if test ! "x$versionmajor" = "x0" || (
+         test ! "x$versionminor" = "x5" &&
+         test ! "x$versionminor" = "x7" &&
+         test ! "x$versionminor" = "x8" &&
+         test ! "x$versionminor" = "x9" ) ; then
          patchneeded="no"
          result "Checking for need of globus patch ... no"
       else
@@ -3875,7 +3979,7 @@ if test "x$enable_globus" = "xyes"; then
       fi
 
    else
-      result "Checking for need of globus patch ... information directory not available"
+      result "information directory not available"
    fi
 
    # Now find includes needed for patch, if the case
@@ -4677,6 +4781,21 @@ if test ! "x$enable_mathmore" = "xno"; then
             result "not found"
         fi
     fi
+    if test "x$enable_mathmore" = "xyes" && \
+       test ! "x$enable_gsl_shared" = "xyes" ; then
+        for gslalib in $gsllibs; do
+           if [ "x`basename $gslalib .a`" != "x`basename $gslalib`" ]; then
+               message "Checking whether $gslalib is compiled with -fPIC"
+               check_libpic $gslalib
+               if test $is_libpic -eq 0 ; then
+                   result "no"
+                   enable_mathmore="no"
+               else
+                   result "yes"
+               fi
+           fi
+        done
+    fi
 fi
 message "Checking whether to build libMathMore"
 if test "x$enable_mathmore" = "xyes"; then
@@ -5221,6 +5340,9 @@ fi
 if test -d math/unuran/src/unuran-1.3.0-root ; then
    rm -rf math/unuran/src/unuran-1.3.0-root
 fi
+if test -d math/unuran/src/unuran-1.5.0-root ; then
+   rm -rf math/unuran/src/unuran-1.5.0-root
+fi
 if test ! "x$enable_editline" = "xno" ; then
    rm -f core/clib/src/Getline.o core/clib/src/Getline.d
 fi
@@ -5236,6 +5358,7 @@ rm -f lib/libMySQL* bin/libMySQL* lib/libGedOld* bin/libGedOld*
 rm -f lib/libSQL.* bin/libSQL.*
 rm -f lib/libASPluginGS.* bin/g2rootold*
 rm -f math/mathcore/src/G__MathCore32.*
+rm -f tmva/src/G__TMVA.*
 rm -f xrootd/src/headers.d
 rm -f asimage/src/headers.d asimage/src/G__ASImageGS.*
 
@@ -5986,20 +6109,18 @@ fi
 if test "x$enable_reflex" = "xyes"; then
     libdirreflex=$libdir
     if test "x$haveconfig" = "x" ; then
-        libdirreflex='`dirname $0`/../lib'
+        libdirreflex='$0; if readlink $dir > /dev/null 2>\&1; then lndir=`readlink $dir`; dir=`dirname $dir`; lndir=`dirname $lndir`; dir=`cd $dir \&\& cd $lndir \&\& pwd \|\| echo $lndir`; else dir=`dirname ${dir}`; fi; dir=${dir}/../lib'
+    fi
+    modpath=""
+    if test "x$platform" = "xwin32"; then
+        modpath=';dir=`cygpath -m $dir`'
     fi
 
-    if test "x$platform" != "xwin32"; then
-        message "Writing $GENREFLEXSHOUT"
-        cat $GENREFLEXSHIN | sed -e "s|@libdir@|$libdirreflex|g" > $GENREFLEXSHOUT
-        chmod a+x $GENREFLEXSHOUT
-        result "done"
-    else
-        message "Writing $GENREFLEXSHOUT"
-        cat $GENREFLEXSHIN | sed -e "s|@libdir@|\$(cygpath -m $libdirreflex)|g" > $GENREFLEXSHOUT
-        chmod a+x $GENREFLEXSHOUT
-        result "done"
-
+    message "Writing $GENREFLEXSHOUT"
+    cat $GENREFLEXSHIN | sed -e "s|@libdir@|$libdirreflex$modpath|g" > $GENREFLEXSHOUT
+    chmod a+x $GENREFLEXSHOUT
+    result "done"
+    if test "x$platform" = "xwin32"; then
         message "Writing $GENREFLEXBATOUT"
         if test "x$haveconfig" = "x" ; then
             libdirreflex='%~d0%~p0\\..\\lib'
