merge with the trunk, revision 44642
git-svn-id: https://root.cern.ch/svn/root/branches/dev/roostats@44644 27541ba8-7e3a-0410-8455-c3a389f83636

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,6 +17,7 @@
 found_lib=no
 found_dir=no
 found_hdr=no
+found_ext=
 show_pkglist=no
 fail_on_missing=no
 noact="no"
@@ -49,14 +50,16 @@ options="                    \
    enable_builtin_pcre       \
    enable_builtin_zlib       \
    enable_builtin_lzma       \
+   enable_cxx11              \
    enable_castor             \
    enable_chirp              \
    enable_cintex             \
    enable_clarens            \
    enable_cling              \
+   enable_cocoa              \
    enable_dcache             \
-   enable_exceptions         \
    enable_explicitlink       \
+   enable_fink               \
    enable_fftw3              \
    enable_fitsio             \
    enable_gviz               \
@@ -137,7 +140,9 @@ for c in $options $deprecated_options; do
 done
 for c in $options ; do eval ${c}_explicit="" ; done
 
+enable_cxx11=no
 enable_cling=no
+enable_cocoa=no
 enable_afs=no
 enable_alloc=no
 enable_gdml=no
@@ -502,6 +507,7 @@ check_library() {
     fi
     found_lib=no
     found_dir=no
+    found_ext=
 
     # Make list of libraries to search for. The .lib extension is for
     # Windoze - note $shared is always "no" on windoze, since we need
@@ -630,6 +636,7 @@ check_library() {
         found_raw_lib=""
         logmsg " library not found"
     else
+        found_ext=`echo $found_lib | sed 's|^lib\(.*\)\.\(.*\)|\2|'`
         flib=""
         maclib=""
         for i in $lib ; do
@@ -832,7 +839,7 @@ check_link() {
        cat <<EOF > conftest.mk
 include ${ac_srcdir}/config/Makefile.${arch}
 conftest: conftest.c
-	\$(CC) \$(CFLAGS) \$(LDFLAGS) $linkdir $linklib \$< -o \$@
+	\$(CC) \$(CFLAGS) \$(LDFLAGS) \$< -o \$@ $linkdir $linklib
 
 conftest.c:
 	echo "int main() { return 0; }" > \$@
@@ -846,7 +853,7 @@ EOF
        cat <<EOF > conftest.mk
 include ${ac_srcdir}/config/Makefile.${arch}
 conftest:conftest.c
-	\$(CC) \$(CFLAGS) \$(LDFLAGS) $linkdir $linklib \$< -o \$@
+	\$(CC) \$(CFLAGS) \$(LDFLAGS) \$< -o \$@ $linkdir $linklib
 
 conftest.c:
 	echo "extern int $linksymbol (); " > \$@
@@ -867,6 +874,48 @@ EOF
     unset linklib
     unset linkdir
     unset linksymbol
+}
+
+#_____________________________________________________________________
+check_cxxopt() {
+    # This function will try to compile with a specific cxx compiler
+    # option [$1]. The result of the check is stored in cxxopt_result,
+    # 1 if true, 0 otherwise, which should be immediately copied,
+    # since the variable will be overwritten at next invocation
+    # of this function.
+
+    # Assert that we got enough arguments
+    if test $# -lt 1 ; then
+        echo "check_compopt: need at least one argument"
+        cxxopt_result=0
+        return 1
+    fi
+
+    # save arguments in logical names
+    cxxopt="$1"; shift
+
+    logmsg " trying to compile with option $cxxopt"
+    cat <<EOF > conftest.mk
+include ${ac_srcdir}/config/Makefile.${arch}
+conftest: conftest.cxx
+	\$(CXX) \$(CFLAGS) $cxxopt \$(LDFLAGS) \$< -o \$@
+
+conftest.cxx:
+	echo "int main() { return 0; }" > \$@
+EOF
+
+    $gnumake -f conftest.mk >> $logfile 2>&1
+    if test $? -eq 0 ; then
+        cxxopt_result=1
+        logmsg " Compilation OK"
+    else
+        cxxopt_result=0
+        logmsg " Failed code was"
+        cat conftest.mk >> $logfile
+    fi
+    rm -rf conftest.cxx conftest.mk conftest conftest.dSYM
+
+    unset cxxopt
 }
 
 #_____________________________________________________________________
@@ -1193,6 +1242,7 @@ guess_architecture() {
         cygwin_*:*86:*)        arch=win32           ;;
         cygwin_*:pentium:*)    arch=win32           ;;
         cygwin_*:ia64)         arch=win32           ;;
+        mingw32_*:*86:*)       arch=win32           ;;
         *)
             echo "Attempts at guessing your architecture failed."
             echo "(triplet is $arch:$chip:$rele)"
@@ -1403,7 +1453,7 @@ FIRST argument one of the architecures given at the end of this message.
    FLAG            DESCRIPTION               DEFAULT
    --aclocaldir    Autoconf macro install dir(<prefix>/share/aclocal)
    --bindir        Binary installation dir   (<prefix>/bin)
-   --build         Build configuration [debug, exceptions, ...],
+   --build         Build configuration [debug, ...],
                    overrides the ROOTBUILD shell variable
    --cintincdir    CINT interpeted headers   (<libdir>/cint)
    --datadir       Data installation dir     (<prefix>/share/root)
@@ -1442,14 +1492,16 @@ enable/disable options, prefix with either --enable- or --disable-
   builtin-pcre       Built included libpcre, or use system libpcre
   builtin-zlib       Built included libz, or use system libz
   builtin-lzma       Built included liblzma, or use system liblzma
+  c++11              Build using C++11 compatible mode, requires gcc > 4.7.x or clang
   castor             CASTOR support, requires libshift from CASTOR >= 1.5.2
   chirp              Chirp filesystem support, requires cctools >= 3.2.2
   cintex             Build the libCintex Reflex interface library
   clarens            Clarens RPC support, optionally used by PROOF
   cling              Use cling as interpreter backend (experimental!), needs --with-llvm-config
+  cocoa              Use native Cocoa/Quartz graphics backend (MacOS X only)
   dcache             dCache support, requires libdcap from DESY
-  exceptions         Turn on compiler exception handling capability
   explicitlink       Explicitly link with all dependent libraries
+  fink               Use libraries from an extra MacOS X package manager (Fink, MacPorts, ...) (default: enabled)
   fftw3              Fast Fourier Transform support, requires libfftw3
   fitsio             Read images and data from FITS files, requires cfitsio
   gviz               Graphs visualization support, requires graphviz
@@ -1529,6 +1581,7 @@ with options, prefix with --with-, enables corresponding support
   dicttype           dictionary type: "cint" (default), "reflex", or "gccxml"
   dnssd-libdir       Bonjour support, location of libdns_sd
   dnssd-incdir       Bonjour support, location of dns_sd.h
+  finkdir            Prefix of extra MacOS X package manager (Fink, MacPorts, ...)
   ftgl-incdir        FTGL support, location of FTGL.h
   ftgl-libdir        FTGL support, location of libftgl
   fftw3-incdir       FFTW3 support, location of fftw3.h
@@ -1743,23 +1796,13 @@ else
    cwhich="which"
 fi
 
-# check for Fink on MacOS X
-# and for sanity of source e.g. pcre-*.tar.gz must exist
+# Check for sanity of source on Mac OS X: e.g. pcre-*.tar.gz must exist
 # which might not be the case if source was unpacked with StuffIt
 if test "x$platform" = "xmacosx" ; then
    if test ! -f ${ac_srcdir}/core/pcre/src/pcre-*.tar.gz ; then
       echo "Source tree does not contain expected files, please unpack"
       echo "using tar and not StuffIt"
       exit 1
-   fi
-   logmsg "Checking Fink directory"
-   finkdir=`$cwhich fink 2>&1 | sed -ne "s/\/bin\/fink//p"`
-   logmsg "$finkdir"
-
-   if test -d /opt/local; then
-      logmsg "Checking MacPorts directory"
-      finkdir=/opt/local
-      logmsg "$finkdir"
    fi
 
    if [ `sw_vers | sed -n 's/ProductVersion://p' | cut -d . -f 2` -ge 5 ]; then
@@ -1779,6 +1822,9 @@ if test "x$platform" = "xlinux" ; then
        if lsb_release -d | grep -i 'debian' > /dev/null 2>& 1; then
           linuxdist="multiarch"
        fi
+       if lsb_release -d | grep -i 'mint' > /dev/null 2>& 1; then
+          linuxdist="multiarch"
+       fi 
     fi
 
     debmultiarch=
@@ -1864,6 +1910,7 @@ if test $# -gt 0 ; then
       --with-dnssd-libdir=*)   dnssdlibdir=$optarg   ; enable_bonjour="yes" ;;
       --with-avahi-incdir=*)   avahiincdir=$optarg   ; enable_bonjour="yes" ;;
       --with-avahi-libdir=*)   avahilibdir=$optarg   ; enable_bonjour="yes" ;;
+      --with-finkdir=*)        finkdir=$optarg       ; enable_fink="yes"    ;;
       --with-ftgl-incdir=*)    ftglincdir=$optarg    ; enable_builtin_ftgl=no;;
       --with-ftgl-libdir=*)    ftgllibdir=$optarg    ; enable_builtin_ftgl=no;;
       --with-fftw3-incdir=*)   fftw3incdir=$optarg   ; enable_fftw3="yes"   ;;
@@ -1951,7 +1998,7 @@ if test $# -gt 0 ; then
       # features
       #
       --enable-*)
-        f=`echo $1 | sed -e 's/--//' -e 's/-/_/g'`
+        f=`echo $1 | sed -e 's/--//' -e 's/-/_/g' -e 's/++11/xx11/'`
         eval prev='$'`echo ${f}`
         eval prev_expl='$'`echo ${f}_explicit`
         if test "${prev}:${prev_expl}" = "yes:"; then
@@ -1980,7 +2027,7 @@ if test $# -gt 0 ; then
         fi
         ;;
       --disable-*)
-        f=`echo $1 | sed -e 's/--disable/enable/' -e 's/-/_/g'`
+        f=`echo $1 | sed -e 's/--disable/enable/' -e 's/-/_/g' -e 's/++11/xx11/'`
         eval prev='$'`echo ${f}`
         eval prev_expl='$'`echo ${f}_explicit`
         if test "${prev}:${prev_expl}" = "xno:"; then
@@ -2078,6 +2125,38 @@ fi
 if test "x$platform" = "xwin32"; then
     enable_shared="no"
     enable_x11="no"
+fi
+
+######################################################################
+#
+### echo %%% Check for Fink or MacPorts on Mac OS X
+#
+if test "x$platform" = "xmacosx"; then
+    message "Checking for Fink/MacPorts directory"
+    if test "x$enable_fink" = "xyes"; then
+        if test -d "$finkdir"; then
+            # User specified a directory with --with-finkdir=...
+            logmsg "Using user-specified Fink directory"
+            logmsg "$finkdir"
+        else
+            # Fink has precedence over MacPorts
+            logmsg "Checking Fink directory"
+            finkdir=`$cwhich fink 2>&1 | sed -ne "s/\/bin\/fink//p"`
+            logmsg "$finkdir"
+
+            if test "x$finkdir" = "x"; then
+                logmsg "Checking MacPorts directory"
+                finkdir=`$cwhich port 2>&1 | sed -ne "s/\/bin\/port//p"`
+                logmsg "$finkdir"
+            fi
+        fi
+        result "$finkdir"
+    else
+        logmsg "Fink/MacPorts disabled"
+        result "disabled"
+    fi
+else
+    enable_fink="no"
 fi
 
 ######################################################################
@@ -2228,6 +2307,40 @@ fi
 
 ######################################################################
 #
+### echo %%% C++11 - compile using c++11 compatible option
+#
+# needs gcc > 4.7.x or clang
+usecxx11="undef"
+if test "x$enable_cxx11" = "xyes"; then
+    message "Checking whether c++11 mode is supported"
+    check_cxxopt -std=c++11
+    if test $cxxopt_result -eq 0 ; then
+        enable_cxx11="no"
+	result "no"
+    else
+	usecxx11="define"
+	result "yes"
+    fi
+fi
+
+######################################################################
+#
+### echo %%% Check if native MacOS X Cocoa/Quartz backend should be build
+#
+if test ! "x$platform" = "xmacosx"; then
+    enable_cocoa="no"
+fi
+
+hascocoa="undef"
+if test "x$enable_cocoa" = "xyes"; then
+    message "Checking whether to build native MacOS X Cocoa backend"
+    hascocoa="define"
+    enable_x11="no"
+    result "yes"
+fi
+
+######################################################################
+#
 ### echo %%% X11 and XPM Library - Mandatory lib on Unix
 #
 # Mandatory test, must succeed
@@ -2361,18 +2474,6 @@ fi
 hasxft="undef"
 if test "x$enable_xft" = "xyes"; then
    hasxft="define"
-fi
-
-######################################################################
-#
-### echo %%% Exceptions - compiler feature
-#
-if test "x$EXCEPTIONS" = "xno" ; then
-    enable_exceptions=no
-fi
-e=`echo $rootbuild | sed 's/.*exceptions.*/1/'`
-if test "x$e" = "x1" ; then
-    enable_exceptions=no
 fi
 
 ######################################################################
@@ -2646,6 +2747,11 @@ if test ! "x$enable_opengl" = "xno" && test ! "x$platform" = "xwin32" ; then
     opengllib=$found_lib
     opengllibdir=$found_dir
 
+    if test ! "x$macosx105" = "x" && test "x$macosx106" = "x" ; then
+	# Mac OS X 10.5 problem
+	opengllib="-dylib_file /usr/X11R6/lib/libGL.dylib:/usr/X11R6/lib/libGL.dylib -lGL"
+    fi
+
     check_library "libGLU libMesaGLU" "$enable_shared" \
         "$keep" $opengllibdirs
     openglulib=$found_lib
@@ -2712,7 +2818,7 @@ if test ! "x$enable_opengl" = "xno" && test ! "x$platform" = "xwin32" ; then
                result "ok"
                ftglincdir=`pkg-config --cflags-only-I ftgl | sed 's/-I//g'`
                ftgllibs=`pkg-config --libs-only-l ftgl`
-               ftgllibdir=`pkg-config --libs-only-L ftgl | sed 's/-L//g'`
+               ftgllibdir=`pkg-config --libs-only-L ftgl`
                enable_builtin_ftgl="no"
             else
                enable_builtin_ftgl="yes"
@@ -3237,8 +3343,12 @@ if test ! "x$enable_rfio" = "xno" ; then
                         break ;
                     fi
                 done
+                message "Checking for symbol rfio_fchmod"
                 if test $link_result -ne 1 ; then
                     enable_rfio="no"
+                    echo "no, disabling rfio"
+                else
+                    echo "yes"
                 fi
                 ;;
            solaris)    shiftlib="$shiftlib -lposix4" ;;
@@ -3329,8 +3439,12 @@ if test ! "x$enable_castor" = "xno" ; then
                         break ;
                     fi
                 done
+                message "Checking for symbol rfio_fchmod"
                 if test $link_result -ne 1 ; then
                     enable_castor="no"
+                    echo "no, disabling castor"
+                else
+                    echo "yes"
                 fi
                 ;;
            solaris)    castorlib="$castorlib -lposix4" ;;
@@ -4465,6 +4579,7 @@ if test "x$enable_xrootd" = "xyes" ; then
       xrdlibs="libXrdNet libXrdOuc libXrdSys libXrdClient libXrd" 
    fi
    tmpxrdlibdir=""
+   xrdlibext=""
    for ll in $xrdlibs ; do 
       #
       # Check if packaging has libXrdUtils or the old libXrdOuc, libXrdSys, ...
@@ -4475,12 +4590,22 @@ if test "x$enable_xrootd" = "xyes" ; then
          xrdlibdir=""
          break
       else
+         xrdlibext="$found_ext"
          tmpxrdlibdir="$found_dir"
          if test "x$ll" = "xlibXrdUtils" || test "x$ll" = "xlibXrdOuc"; then
             libxrdoucbjr="$found_lib"
          fi
       fi
    done
+
+   #
+   # If not 'so' or 'a', comunicate the extension for the library loadings
+   # in XrdProofd. This may be temporary, as xrootd may do it automatically,
+   # one day ...
+   if test ! "x$xrdlibext" = "x" && test ! "x$xrdlibext" = "xso" && test ! "x$xrdlibext" = "xa"; then
+      # The \'s are needed to produce -DLT_MODULE_EXT=\".ext\" in Makefile.config
+      extraxrdflags="$extraxrdflags -DLT_MODULE_EXT=\\\\\".$xrdlibext\\\\\""
+   fi
 
    #
    # Check if bonjour is available for code potentially using it ...
@@ -6264,7 +6389,10 @@ rm -f lib/libRXML* bin/libRXML* etc/system.rootmap \
  core/utils/src/rootcint7.cxx core/utils/src/RStl7.cxx \
  core/metautils/src/TClassEdit7.cxx \
  core/metautils/src/RConversionRuleParser7.cxx \
+ core/meta/src/G__TCint.h core/meta/src/G__TCint.cxx \
  core/thread/src/TLockFile.* proof/proofplayer/src/TFileMerger.* \
+ graf2d/graf/src/G__Graf1.h graf2d/graf/src/G__Graf1.cxx \
+ graf2d/graf/src/G__Graf2.h graf2d/graf/src/G__Graf2.cxx \
  etc/daemons/olbd.rc.d etc/daemons/cmsd.rc.d etc/daemons/xrootd.rc.d \
  bin/cmsd bin/xprep bin/xrd bin/xrdcp bin/xrdgsiproxy bin/xrdpwdadmin \
  bin/xrdsssadmin bin/xrdstagetool bin/xrootd lib/libXrd* \
@@ -6504,7 +6632,6 @@ sed -e "s|@aclocaldir@|$aclocaldir|"            \
     -e "s|@buildmemstat@|$enable_memstat|"      \
     -e "s|@enable_thread@|$enable_thread|"      \
     -e "s|@etcdir@|$etcdir|"                    \
-    -e "s|@exceptions@|$enable_exceptions|"     \
     -e "s|@explicitlink@|$enable_explicitlink|" \
     -e "s|@gfalincdir@|$gfalincdir|"            \
     -e "s|@gfallib@|$gfallib|"                  \
@@ -6680,6 +6807,8 @@ sed -e "s|@srcdir@|$ac_srcdir|"                 \
     -e "s|@buildafdsmgrd@|$enable_afdsmgrd|"    \
     -e "s|@afdsmgrdapmon@|$afdsmgrdapmon|"      \
     -e "s|@buildglite@|$enable_glite|"          \
+    -e "s|@buildcocoa@|$enable_cocoa|"          \
+    -e "s|@c++11@|$enable_cxx11|"               \
     < Makefile.tmp > $MAKEOUT
 rm -f Makefile.tmp
 
@@ -6731,6 +6860,8 @@ sed \
     -e "s|@haspthread@|$haspthread|"       \
     -e "s|@hasxft@|$hasxft|"               \
     -e "s|@hascling@|$hascling|"           \
+    -e "s|@hascocoa@|$hascocoa|"           \
+    -e "s|@usec++11@|$usecxx11|"           \
     < RConfigure.tmp > RConfigure-out.tmp
 rm -f RConfigure.tmp
 
